const PREFIX = "AUTH";

export const LOGIN_REQUEST = `${PREFIX}/LOGIN_REQUEST`;
export const LOGIN_SUCCESS = `${PREFIX}/LOGIN_SUCCESS`;
export const LOGIN_FAILURE = `${PREFIX}/LOGIN_FAILURE`;

export const REGISTER_REQUEST = `${PREFIX}/REGISTER_REQUEST`;
export const REGISTER_SUCCESS = `${PREFIX}/REGISTER_SUCCESS`;
export const REGISTER_FAILURE = `${PREFIX}/REGISTER_FAILURE`;