const PREFIX = "PROFILE"

const USERPROFILE_REQUEST = `${PREFIX}/USERPROFILE_REQUEST`
const USERPROFILE_SUCCESS = `${PREFIX}/USERPROFILE_SUCCESS`
const USERPROFILE_FAILURE = `${PREFIX}/USERPROFILE_FAILURE`

export {USERPROFILE_REQUEST,USERPROFILE_SUCCESS,USERPROFILE_FAILURE}